![image-20200128220225591](C:\Users\Hery\Desktop\GitHub\java\image\image-20200128220225591.png)

# try-catch

```java
public static void method() {
    try {
        int[] arr = {1, 2, 3};
        System.out.println(arr[3]);
        System.out.println("这里能够访问到吗");
    } catch (ArrayIndexOutOfBoundsException e) {
        System.out.println("你访问的数组索引不存在，请回去修改为正确的索引");
        e.printStackTrace();
    }
}
```

# thowable类

异常最高级父类

| 方法名                        | 说明                              |
| ----------------------------- | --------------------------------- |
| public String getMessage()    | 返回此 throwable 的详细消息字符串 |
| public String toString()      | 返回此可抛出的简短描述            |
| public void printStackTrace() | 把异常的错误信息输出在控制台      |

# 编译时异常&运行时异常

**==编译时异常==**

​	都是Exception类及其子类
​	必须显示处理，否则程序就会发生错误，无法通过编译

**try-catch或者throws，如果采用throws，谁调用谁处理**

**==运行时异常==**

​	都是RuntimeException类及其子类
​	无需显示处理，也可以和编译时异常一样处理  

**可以不处理，直接回来改代码**

```java
public class ThrowsDemo {
    public static void main(String[] args) {
        System.out.println("begin");
        try {
            //method();
            method2();
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("end");
    }
    //运行时异常
    public static void method() {
        int arr[] = {1, 2, 3};
        System.out.println(arr[3]);
    }
    //编译时异常
    public static void method2() throws ParseException {
        String s = "2018-08-08";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date d = sdf.parse(s);
        System.out.println(d);
    }
}
```

# 自定义异常

![image-20200129213353568](C:\Users\Hery\Desktop\GitHub\java\image\image-20200129213353568.png)



自定义异常类继承于Exception类

```java
public class ScoreException extends Exception {
    public ScoreException() {
    }

    public ScoreException(String message) {
        super(message);
    }
}
```

方法声明时**throws**代表可能发生==异常类名==，不一定发生

具体代码块中需要**throw**==异常对象==，才能在被调用时==catch==

```java
public class Teacher {
    public void score(int s) throws ScoreException{
        if(s<=0||s>=100){
            throw new ScoreException("wrong score");
        }else{
            System.out.println("score="+s);
        }
    }
}
```

```java
public class Test {
    public static void main(String[] args) {
        Teacher t=new Teacher();
        try {
            t.score(-5);//可能抛出message=wrong score的ScoreException类异常
        } catch (ScoreException e) //形参接收{
            e.printStackTrace();
        }
    }
}
```

